# Generated by Django 5.2.13 on 2026-04-14 05:04

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_add_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='document',
            field=models.FileField(blank=True, help_text='PDF only, max 5 MB.', null=True, upload_to='students/docs/', validators=[account.validators.validate_student_pdf]),
        ),
        migrations.AddField(
            model_name='student',
            name='student_photo',
            field=models.ImageField(blank=True, help_text='JPG or PNG, max 2 MB (stored optimized 500×500 max, JPEG).', null=True, upload_to='students/photos/', validators=[account.validators.validate_student_image]),
        ),
    ]
